# This file describes the keymaps that will be built by the GitHub Actions CI.

include:

  # Quacken Zero + SparkFun RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: quacken_zero
    artifact-name: quacken_zero
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex
  - board: quacken_flex
    artifact-name: quacken_flex
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y


  ###
  # Keymap Checks: dummy keeb + command-line options
  ##

  # making sure we can build for the RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: tester_pro_micro
    artifact-name: __tester
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS"

  # Qwerty + Vim + hrm_shift
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: tester_pro_micro
    artifact-name: __test_qwerty_vim_shift
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS;-DVIM_NAVIGATION;-DHRM_SHIFT"

  # Azerty + thumb-taps
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: tester_pro_micro
    artifact-name: __tester_azerty_tt
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS;-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"

  # Ergol + Hummingbird
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: tester_pro_micro
    artifact-name: __tester_ergol_hummingbird
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS;-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
