# This file describes the keymaps that will be built by the GitHub Actions CI.

include:

  # dummy firmware, just making sure we can build for the RP2040
  - board: sparkfun_pro_micro_rp2040
    shield: tester_pro_micro
    artifact-name: quacken_test
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Zero + SparkFun RP2040
  - board: sparkfun_pro_micro_rp2040
    shield: quacken_zero
    artifact-name: quacken_zero
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex
  - board: quacken_flex
    artifact-name: quacken_flex
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex, Azerty
  - board: quacken_flex
    artifact-name: quacken_flex_azerty
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY"
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex, Bépo
  - board: quacken_flex
    artifact-name: quacken_flex_bepo
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_BEPO"
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex, Bépolar
  - board: quacken_flex
    artifact-name: quacken_flex_bepolar
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_BEPOLAR"
      -DCONFIG_ZMK_STUDIO=y
