#!/usr/bin/env bash
TARGET=$1
LAYOUT=$2

# uncomment the following line to enable USB logging
USB_LOGGING="-S zmk-usb-logging"

# uncomment the following lines to enable ZMK Studio support
ZMK_STUDIO_SNIPPET="-S studio-rpc-usb-uart"
ZMK_STUDIO_CMAKE="-DCONFIG_ZMK_STUDIO=y"

# target: Quacken Flex or Quacken Zero
# - Ergogen keebs rely on an MCU board, the keeb itself is just a shield
# - keebs with an integrated MCU are custom boards and don’t use any shield
BOARD=
SHIELD=
case $TARGET in
flex)
	BOARD="-b quacken_flex"
	;;
zero)
	BOARD="-b sparkfun_pro_micro_rp2040//zmk"
	SHIELD="-DSHIELD=quacken_zero"
	;;
test)
	BOARD="-b sparkfun_pro_micro_rp2040//zmk"
	SHIELD="-DSHIELD=tester_pro_micro" # 'naked60' would work as well
	;;
*)
	echo "Usage:"
	echo "    $0 TARGET LAYOUT"
	echo
	echo "where TARGET can be:"
	echo "    - flex: Quacken Flex 25.10+ / embedded RP2040"
	echo "    - zero: Quacken Zero 25.07+ / SparkFun Pro Micro RP2040"
	echo "    - test: dummy tester shield / SparkFun Pro Micro RP2040"
	echo
	echo "and LAYOUT can be:"
	echo "    - qwerty"
	echo "    - dvorak"
	echo "    - azerty"
	echo "    - ergol"
	echo "    - erglace"
	echo "    - bepo"
	echo "    - bepolar"
	echo "    - lafayette"
	echo
	exit 1
	;;
esac

# ensure we have a symlink to a proper ZMK setup
FILE_ROOT="zmk_quacken_${TARGET}_${LAYOUT}"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ZMK_APP_DIR=$SCRIPT_DIR/zmk/app
if [ ! -d $ZMK_APP_DIR ]; then
	echo "Expecting a 'zmk' symlink to your local ZMK/Zephyr setup. Aborting."
	exit 1
fi

# build
cd $ZMK_APP_DIR
source ../.venv/bin/activate

build() {
	touch build/zephyr/zmk.uf2
	HT_FLAGS="-DKB_LAYOUT_${LAYOUT^^};-DHT_$2"
	FILE_NAME="${FILE_ROOT}_$1.uf2"
	west build $USB_LOGGING $ZMK_STUDIO_SNIPPET $BOARD -- $SHIELD \
		$ZMK_STUDIO_CMAKE \
		-DKEYMAP_FILE="$SCRIPT_DIR/keymaps/quacken.keymap" \
		-DZMK_EXTRA_MODULES="$SCRIPT_DIR" \
		-DDTS_EXTRA_CPPFLAGS="$HT_FLAGS;$CPP_FLAGS"
	mv build/zephyr/zmk.uf2 "$SCRIPT_DIR/$FILE_NAME"
}

# PC: classic/Vim flavors
CPP_FLAGS=""
build ez NONE
build tt THUMB_TAPS
build hrm HOME_ROW_MODS
build 2tk TWO_THUMB_KEYS
CPP_FLAGS="-DVIM_NAVIGATION"
build ez_vim NONE
build tt_vim THUMB_TAPS
build hrm_vim HOME_ROW_MODS
build 2tk_vim TWO_THUMB_KEYS

# Mac: classic/Vim flavors
CPP_FLAGS="-DMACOS"
build mac_ez NONE
build mac_tt THUMB_TAPS
build mac_hrm HOME_ROW_MODS
build mac_2tk TWO_THUMB_KEYS
CPP_FLAGS="-DMACOS;-DVIM_NAVIGATION"
build mac_ez_vim NONE
build mac_tt_vim THUMB_TAPS
build mac_hrm_vim HOME_ROW_MODS
build mac_2tk_vim TWO_THUMB_KEYS

# Zip archives
cd $SCRIPT_DIR
zip ${FILE_ROOT}_mac.zip ${FILE_ROOT}_mac*.uf2
rm ${FILE_ROOT}_mac*.uf2
zip $FILE_ROOT.zip ${FILE_ROOT}*.uf2
rm ${FILE_ROOT}*.uf2
ls -l ${FILE_ROOT}*.zip
