#!/usr/bin/env bash
TARGET=$1
LAYOUT=$2
FILE_ROOT="zmk_quacken_${TARGET}_${LAYOUT}"

# uncomment the following line to enable USB logging
USB_LOGGING="-S zmk-usb-logging"

# uncomment the following lines to enable ZMK Studio support
ZMK_STUDIO_SNIPPET="-S studio-rpc-usb-uart"
ZMK_STUDIO_CMAKE="-DCONFIG_ZMK_STUDIO=y"

usage() {
	echo "Usage:"
	echo "    $0 TARGET LAYOUT"
	echo
	echo "where TARGET can be:"
	echo "    - flex: Quacken Flex 25.10+ / embedded RP2040"
	echo "    - zero: Quacken Zero 25.07+ / SparkFun Pro Micro RP2040"
	echo "    - test: dummy tester shield / SparkFun Pro Micro RP2040"
	echo
	echo "and LAYOUT can be either a host layout:"
	echo "    - qwerty"
	echo "    - qwerty_intl"
	echo "    - qwerty_lafayette"
	echo "    - dvorak"
	echo "    - azerty"
	echo "    - ergol"
	echo "    - erglace"
	echo "    - bepo"
	echo "    - bepolar"
	echo
	echo "or a layout emulation description:"
	echo "    - qwerty_to_dvorak"
	echo "    - azerty_to_ergol"
	echo "    - qwerty_intl_to_ergol"
	echo
	exit 1
}

# target: Quacken Flex or Quacken Zero
# - Ergogen keebs rely on an MCU board, the keeb itself is just a shield
# - keebs with an integrated MCU are custom boards and don’t use any shield
BOARD=
SHIELD=
case $TARGET in
flex)
	BOARD="-b quacken_flex"
	;;
zero)
	BOARD="-b sparkfun_pro_micro_rp2040//zmk"
	SHIELD="-DSHIELD=quacken_zero"
	;;
test)
	BOARD="-b sparkfun_pro_micro_rp2040//zmk"
	SHIELD="-DSHIELD=tester_pro_micro" # 'naked60' would work as well
	;;
*)
	usage
	;;
esac

# layout: host layout or emulation
EMULATION=
case $LAYOUT in
qwerty) ;;
qwerty_intl) ;;
qwerty_lafayette) ;;
dvorak) ;;
azerty) ;;
ergol) ;;
erglace) ;;
bepo) ;;
bepolar) ;;
qwerty_to_dvorak)
	$LAYOUT=qwerty
	$EMULATION="-DKB_EMULATION_DVORAK"
	;;
azerty_to_ergol)
	$LAYOUT=azerty
	$EMULATION="-DKB_EMULATION_ERGOL"
	;;
qwerty_intl_to_ergol)
	$LAYOUT=qwerty_intl
	$EMULATION="-DKB_EMULATION_ERGOL"
	;;
*)
	usage
	;;
esac

# ensure we have a symlink to a proper ZMK setup
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
ZMK_APP_DIR=$SCRIPT_DIR/zmk/app
if [ ! -d $ZMK_APP_DIR ]; then
	echo "Expecting a 'zmk' symlink to your local ZMK/Zephyr setup. Aborting."
	exit 1
fi

# build
cd $ZMK_APP_DIR
source ../.venv/bin/activate

build() {
	touch build/zephyr/zmk.uf2
	FILE_PATH="$SCRIPT_DIR/${FILE_ROOT}$1.uf2"
	CPP_FLAGS="-DKB_LAYOUT_${LAYOUT^^};-DHT_$2;$EMULATION;$OPT_FLAGS"
	west build $USB_LOGGING $ZMK_STUDIO_SNIPPET $BOARD -- $SHIELD \
		$ZMK_STUDIO_CMAKE \
		-DKEYMAP_FILE="$SCRIPT_DIR/keymaps/quacken.keymap" \
		-DZMK_EXTRA_MODULES="$SCRIPT_DIR" \
		-DDTS_EXTRA_CPPFLAGS="$CPP_FLAGS"
	mv build/zephyr/zmk.uf2 "$FILE_PATH"
}

# Build PC flavors
OPT_FLAGS=""
build [pc]_ez NONE
build [pc]_tt THUMB_TAPS
build [pc]_hrm HOME_ROW_MODS
build [pc]_2tk TWO_THUMB_KEYS
OPT_FLAGS="-DVIM_NAVIGATION"
build [pc]_ez_vim NONE
build [pc]_tt_vim THUMB_TAPS
build [pc]_hrm_vim HOME_ROW_MODS
build [pc]_2tk_vim TWO_THUMB_KEYS

# Build Mac flavors
OPT_FLAGS="-DMACOS"
build [mac]_ez NONE
build [mac]_tt THUMB_TAPS
build [mac]_hrm HOME_ROW_MODS
build [mac]_2tk TWO_THUMB_KEYS
OPT_FLAGS="-DMACOS;-DVIM_NAVIGATION"
build [mac]_ez_vim NONE
build [mac]_tt_vim THUMB_TAPS
build [mac]_hrm_vim HOME_ROW_MODS
build [mac]_2tk_vim TWO_THUMB_KEYS

# Zip archives
cd $SCRIPT_DIR
zip ${FILE_ROOT}[pc].zip ${FILE_ROOT}[pc]*.uf2
zip ${FILE_ROOT}[mac].zip ${FILE_ROOT}[mac]*.uf2
rm ${FILE_ROOT}[pc]*.uf2
rm ${FILE_ROOT}[mac]*.uf2
ls -l ${FILE_ROOT}*.zip
