# This file describes the keymaps that will be built by the GitHub actions CI.
# Each keymap is an "artefact", whose name goes as follows :
#
# `quacken_[board]_[dual_keys]_[lefty]_[shift]_[layout]`
#
# - board (required): specifies the kind of board the firmware is meant for
#   - flex (integrated rp2040 micro-controller, any version number)
#   - zero (promicro, you’ll have to update the `board` field to have your actual promicro board)
# - dual_keys (required): specifies the flavor of tap/hold keys used in the keympap
#   - ez  (no dual keys, VERY simple config, recommended for anxious users)
#   - lt  (layer taps on thumb keys, recommended for neophytes)
#   - hrm (home-row-mods enabled and refactored thumb keys, recommended for intermediate users)
#   - vim (same as `hrm`, but with separate layers for navigation and numbers, recommended for advanced users)
# - lefty  (optionnal): if specified, put space on the left thumb instead of the right thumb.
# - shift  (optionnal): if specified, add shift as a pinky home-row-mod. Usefull for shortcuts, NOT MEANT to type text
# - layout (optionnal): if specified, change the underlying layout from qwerty to one of:
#   - azerty
#   - ergol
#   - ...probably more in the future

include:
  - board: quacken_flex
    artifact-name: quacken_flex_hrm
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DDUAL_KEYS=HOME_ROW_MODS"

  - board: quacken_flex
    artifact-name: quacken_flex_vim_ergol
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS=\"
        -DALIASES_FILE_PATH=aliases_ergol.h
        -DDUAL_KEYS=HOME_ROW_MODS_VIM
      \"

  - board: sparkfun_pro_micro_rp2040
    shield: quacken_zero
    artifact-name: quacken_zero_hrm
    cmake-args: -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap

