# CONFIG_KB_LAYOUT_Qwerty is not set
# CONFIG_KB_LAYOUT_QWERTY_LAFAYETTE is not set
# CONFIG_KB_LAYOUT_AZERTY is not set
# CONFIG_KB_LAYOUT_ERGOL is not set
# CONFIG_KB_LAYOUT_DVORAK is not set
# CONFIG_KB_LAYOUT_BEPO is not set
CONFIG_KB_LAYOUT_BEPOLAR=y

# CONFIG_HT_NONE is not set
CONFIG_HT_THUMB_TAPS=y
# CONFIG_HT_HOME_ROW_MODS is not set
# CONFIG_HT_TWO_THUMB_KEYS is not set
CONFIG_TAPPING_TERM=300
CONFIG_SHORT_TAPPING_TERM=150
CONFIG_QUICK_TAPPING_TERM=200
CONFIG_VIM_NAVIGATION=y
CONFIG_HRM_SHIFT=y
# CONFIG_MACOS is not set
