manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: OneDeadKey
      url-base: https://github.com/Nuclear-Squid
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: c62da0e16646d10240ba29191bdbcb5611b3a1af
      import: app/west.yml
    - name: zmk-config-aekeynox
      remote: OneDeadKey
      revision: zephyr_module_test
  self:
    path: config
